### ISSUE TITLE
layout not correct

### ISSUE THREAD

**Issue by funkyduke** [Jako/LangSuggest#7]
The layout of the modal is not correct. The close button and the title are not placed good. See screenshot.

I know I can override the chunk, but I mention it because it's better if it already looks good out of the box. ;-)

![afbeelding](https://user-images.githubusercontent.com/1769979/123636262-ee157680-d81c-11eb-9d6a-e3047775d242.png)

**Comment by Jako** [comment]
The default chunk is based on Bootstrap 3 for historical reasons. Maybe that's the reason for your issue.
