### ISSUE TITLE
ru + uk language 

### ISSUE THREAD

**Issue by modx-lab** [Jako/LangSuggest#8]
dont show 

log:

[2021-09-30 12:32:23] (ERROR in LangSuggest @ /home/xxx/xxx/www/core/components/langsuggest/src/LangSuggest.php : 270) LangSuggest is shown.
[2021-09-30 12:32:23] (ERROR in LangSuggest @ /home/xxx/xxx/www/core/components/langsuggest/src/LangSuggest.php : 271) Placeholder: Array
(
    [cookie_name] => LangSuggest
    [cookie_expiration] => 365
    [current_id] => 6
    [redirect_id] => 6
    [debug] => 1
    [cultureKey] => ru
)

**Comment by modx-lab** [comment]
browser language - english

id 6 = error page in system settings

**Comment by Jako** [comment]
Do you have an URL for me to check this?

**Comment by modx-lab** [comment]
xxx

jako
uPEn9t

**Comment by Jako** [comment]
On this page the popup is displayed: https://xeonet.com.ua/uk/

**Comment by modx-lab** [comment]
i dont have popup :( 

uk/?langsuggest_reset=1

**Comment by Jako** [comment]
It is quite easy: LangSuggest can't work on the `error_page` if the routing is not working right. It can't replace the resource content there.

I have changed the logging messages a bit.

**Comment by modx-lab** [comment]
strange, because the site is now published and should not be like this

**Comment by modx-lab** [comment]
Or need to create a 404 page for each context?

**Comment by modx-lab** [comment]
very strange, made separate error pages, revised redirects and the pages give 200 code

does not show :(

**Comment by Jako** [comment]
Please fix the context routing before working with LangSuggest.
